languageCode = "es-ES"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20