baseURL = 'https://lolivera86.github.io/blog.github.io/'
languageCode = 'es-ES'
title = 'Coaching con ciencia'
[[module.imports]]
path = 'github.com/gethinode/hinode'


languageCode = "es-ES"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false