[[main]]
  name = "About"
  pageRef = "/blog.github.io/about/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "/blog.github.io/blog/"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 30

[[main]]
  name = "Sample project"
  pageRef = "/blog.github.io/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[main]]
  name = "Another project"
  pageRef = "/blog.github.io/projects/another-project/"
  parent = "Projects"
  weight = 2

[[main]]
  name = "Tags"
  pageRef = "/blog.github.io/tags/"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10


# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation